server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: seller-service
          uri: http://localhost:8081
          order: 1
          predicates:
            - Path=/api/admin/apply/list, /api/admin/*/approve, /api/admin/*/reject, /api/admin/seller/*/apply, /api/user/seller/apply, /api/user/*/modify, /api/user/*/cancel, /api/user/reject/reason

        - id: product-service
          uri: http://localhost:8082
          order: 2
          predicates:
            - Path=/api/product/**, /api/admin/*/product

        - id: order-service
          uri: http://localhost:8083
          order: 3
          predicates:
            - Path=/api/order/**, /api/admin/*/order

        - id: bid-service
          uri: http://localhost:8084
          order: 4
          predicates:
            - Path=/api/auction/**, /api/admin/*/bid, /api/admin/*/bid-list/*

        - id: category-service
          uri: http://localhost:8086
          order: 5
          predicates:
            - Path=/api/category/**

        - id: rating-service
          uri: http://localhost:8087
          order: 6
          predicates:
            - Path=/api/rating/**

        - id: user-service
          uri: http://localhost:8085
          order: 100
          predicates:
            - Path=/api/user/**, /api/auth/**, /api/admin/**